name: Test Environment Export

on:
  push:
    branches:
      - develop

jobs:
  export-secrets:
    name: Export Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export Environment Variables
        run: |
          echo "OSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }}" >> $GITHUB_ENV
          echo "OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}" >> $GITHUB_ENV
          echo "PGP_PASSPHRASE=${{ secrets.PGP_PASSPHRASE }}" >> $GITHUB_ENV

      - name: Verify Environment Variables
        run: |
          echo "Environment variables exported successfully"
