name: Test Environment Export

on:
  push:
    branches:
      - develop

jobs:
  export-secrets:
    name: Export Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Give gradlew execute permissions
        run: chmod +x ./gradlew

      - name: Save PGP Private Key to file
        run: echo "${{ secrets.PGP_PRIVATE_KEY }}" > private_key.asc

      - name: Import PGP Key
        run: gpg --batch --import private_key.asc

      - name: Encode PGP Private Key to base64
        run: |
          base64 private_key.asc > private_key_base64.asc
          echo "PGP_PRIVATE_KEY_BASE64=$(cat private_key_base64.asc)" >> $GITHUB_ENV

      - name: Verify base64 encoded PGP Private Key
        run: |
          echo "${{ env.PGP_PRIVATE_KEY_BASE64 }}" | base64 --decode > decoded_private_key.asc
          gpg --batch --import decoded_private_key.asc
